spring.application.name=Financial-data-warehouse
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/financial_dwh
warehouse.seed-sample-data=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
